version: '3.9'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - ""
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/usr/share/nginx/html/static
    ports:
      - ""
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
